## Import Libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Import data

In [2]:
(X_train, y_train), (X_test, y_test) = keras.datasets.fashion_mnist.load_data()

## Shape of training data

In [3]:
np.set_printoptions(linewidth=200, formatter={'float': lambda x: "{0:0.2f}".format(x)})

print(X_train[1])

[[  0   0   0   0   0   1   0   0   0   0  41 188 103  54  48  43  87 168 133  16   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0  49 136 219 216 228 236 255 255 255 255 217 215 254 231 160  45   0   0   0   0   0]
 [  0   0   0   0   0  14 176 222 224 212 203 198 196 200 215 204 202 201 201 201 209 218 224 164   0   0   0   0]
 [  0   0   0   0   0 188 219 200 198 202 198 199 199 201 196 198 198 200 200 200 200 201 200 225  41   0   0   0]
 [  0   0   0   0  51 219 199 203 203 212 238 248 250 245 249 246 247 252 248 235 207 203 203 222 140   0   0   0]
 [  0   0   0   0 116 226 206 204 207 204 101  75  47  73  48  50  45  51  63 113 222 202 206 220 224   0   0   0]
 [  0   0   0   0 200 222 209 203 215 200   0  70  98   0 103  59  68  71  49   0 219 206 214 210 250  38   0   0]
 [  0   0   0   0 247 218 212 210 215 214   0 254 243 139 255 174 251 255 205   0 215 217 214 208 220  95   0   0]
 [  0   0   0  45 226 214 214 215 224 205   0  42  35  60  16  17  12  13  70   

In [16]:
X_train.dtype

dtype('uint8')

## Matrix into image

In [4]:
from PIL import Image
Image.fromarray(X_train[1])

In [5]:
X_train = X_train/255.0
X_test = X_test/255.0

## NN model

In [10]:
# This Callback class will stop the number of times training example runs(i.e. epochs) once it reaches the set condition of accuracy or loss

class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('acc') > 0.6): # Try "accuracy" instead of "acc" in case of error
            print("\nReached 60% accuracy so cancelling training!")
            self.model.stop_training = True

In [11]:
callbacks = myCallback()

model = keras.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer=tf.optimizers.Adam(), loss="sparse_categorical_crossentropy", metrics="accuracy")
model.fit(X_train, y_train, epochs=5, callbacks=[callbacks])

Epoch 1/5
1875/1875 [==============================] - 2s 894us/step - loss: 0.5068 - accuracy: 0.8236

Reached 60% accuracy so cancelling training!


In [12]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.4521 - accuracy: 0.8357


[0.45212969183921814, 0.8356999754905701]

## CNN model

In [35]:
X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28, 28, 1)

In [36]:
cnn_model = keras.Sequential([
    keras.layers.Conv2D(64, (3,3), activation="relu", input_shape=(28,28,1)),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Conv2D(64, (3,3), activation="relu"),
    keras.layers.MaxPooling2D(2,2),
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(10, activation="softmax")

])

cnn_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics="accuracy")
cnn_model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 33s 17ms/step - loss: 0.4402 - accuracy: 0.8409
Epoch 2/5
1875/1875 [==============================] - 34s 18ms/step - loss: 0.2888 - accuracy: 0.8942
Epoch 3/5
1875/1875 [==============================] - 34s 18ms/step - loss: 0.2452 - accuracy: 0.9094
Epoch 4/5
1875/1875 [==============================] - 36s 19ms/step - loss: 0.2127 - accuracy: 0.9210
Epoch 5/5
1875/1875 [==============================] - 33s 17ms/step - loss: 0.1868 - accuracy: 0.9300


In [32]:
cnn_model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 26, 26, 64)        640       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 13, 13, 64)        0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 11, 11, 64)        36928     
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dense_18 (Dense)             (None, 128)               204928    
_________________________________________________________________
dense_19 (Dense)             (None, 10)               